In [1]:
import pandas as pd

c:\Users\macau\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [9]:
df1 = pd.read_csv('DadosBrutos/leads_basic_details.csv')
df2 = pd.read_csv('DadosBrutos/leads_demo_watched_details.csv')
df3 = pd.read_csv('DadosBrutos/leads_interaction_details.csv')
df4 = pd.read_csv('DadosBrutos/leads_reasons_for_no_interest.csv')
df5 = pd.read_csv('DadosBrutos/sales_managers_assigned_leads_details.csv')

In [8]:
df1.isnull().sum()

lead_id              0
age                  0
gender               0
current_city         0
current_education    0
parent_occupation    0
lead_gen_source      0
dtype: int64

In [10]:
df2.isnull().sum()

lead_id               0
demo_watched_date     0
language              0
watched_percentage    0
dtype: int64

In [11]:
df3.isnull().sum()

jnr_sm_id         0
lead_id           0
lead_stage        0
call_done_date    0
call_status       0
call_reason       0
dtype: int64

In [12]:
df4.isnull().sum()

lead_id                                     0
reasons_for_not_interested_in_demo        130
reasons_for_not_interested_to_consider    215
reasons_for_not_interested_to_convert     243
dtype: int64

In [13]:
df4.shape

(294, 4)

In [14]:
df4.head()

,lead_id,reasons_for_not_interested_in_demo,reasons_for_not_interested_to_consider,reasons_for_not_interested_to_convert
0,USR1001,No time for student,NaN,NaN
1,USR1003,NaN,No time for student,NaN
2,USR1004,NaN,Wants offline classes,NaN
3,USR1005,NaN,Can't afford,NaN
4,USR1006,NaN,Student not interested in domain,NaN

In [16]:
df4['reasons_for_not_interested_in_demo'].unique()

array(['No time for student', nan, 'Student not interested in domain',
       'Wants offline classes', "Can't afford", 'Cannot afford',
       'Will join in final year'], dtype=object)

In [19]:
traduzido = {
    'lead_id': 'id_lead',
    'reasons_for_not_interested_in_demo': 'motivo_nao_demo',
    'reasons_for_not_interested_to_consider': 'motivo_nao_consideracao',
    'reasons_for_not_interested_to_convert': 'motivo_nao_conversao'
}

df4 = df4.rename(columns=traduzido)

In [20]:
df4.head()

,id_lead,motivo_nao_demo,motivo_nao_consideracao,motivo_nao_conversao
0,USR1001,No time for student,NaN,NaN
1,USR1003,NaN,No time for student,NaN
2,USR1004,NaN,Wants offline classes,NaN
3,USR1005,NaN,Can't afford,NaN
4,USR1006,NaN,Student not interested in domain,NaN

In [21]:
df1.columns

Index(['lead_id', 'age', 'gender', 'current_city', 'current_education',
       'parent_occupation', 'lead_gen_source'],
      dtype='object')

In [22]:
traduzido1 = {
    'lead_id': 'id_lead',
    'age': 'idade',
    'gender': 'genero',
    'current_city': 'cidade_atual',
    'current_education': 'escolaridade_atual',
    'parent_occupation': 'ocupacao_pais',
    'lead_gen_source': 'origem_lead'
}

df1 = df1.rename(columns=traduzido1)

In [23]:
df1.head()

,id_lead,idade,genero,cidade_atual,escolaridade_atual,ocupacao_pais,origem_lead
0,USR1001,16,FEMALE,Hyderabad,Intermediate,Private Employee,social_media
1,USR1002,20,MALE,Bengaluru,B.Tech,Business,user_referrals
2,USR1003,20,FEMALE,Visakhapatnam,B.Tech,Lawyer,user_referrals
3,USR1004,16,MALE,Mumbai,Intermediate,IT Employee,user_referrals
4,USR1005,16,MALE,Chennai,Intermediate,Government Employee,user_referrals

In [24]:
df2.head()

   lead_id demo_watched_date language  watched_percentage
0  USR1002          1/4/2022   Telugu                  42
1  USR1003          1/7/2022   Telugu                  81
2  USR1004          1/2/2022   Telugu                  35
3  USR1005          1/3/2022    Hindi                  38
4  USR1006         1/12/2022    Hindi                  54

In [25]:
df2.isnull().sum()

lead_id               0
demo_watched_date     0
language              0
watched_percentage    0
dtype: int64

In [26]:
df2.duplicated().sum()

0

In [28]:
df2.columns

Index(['lead_id', 'demo_watched_date', 'language', 'watched_percentage'], dtype='object')

In [29]:
traduzido2 = {
    'lead_id': 'id_lead',
    'demo_watched_date': 'data_demo_assistida',
    'language': 'linguagem',
    'watched_percentage': 'porcentagem_assistida'
}
df2 = df2.rename(columns=traduzido2)

In [30]:
df2.head()

   id_lead data_demo_assistida linguagem  porcentagem_assistida
0  USR1002            1/4/2022    Telugu                     42
1  USR1003            1/7/2022    Telugu                     81
2  USR1004            1/2/2022    Telugu                     35
3  USR1005            1/3/2022     Hindi                     38
4  USR1006           1/12/2022     Hindi                     54

In [37]:
df3.head()

,jnr_sm_id,lead_id,lead_stage,call_done_date,call_status,call_reason
0,JNR1001MG,USR1001,lead,1/2/2022,successful,lead_introduction
1,JNR1001MG,USR1001,lead,1/2/2022,successful,demo_schedule
2,JNR1001MG,USR1002,lead,1/3/2022,successful,lead_introduction
3,JNR1001MG,USR1002,lead,1/4/2022,successful,demo_schedule
4,JNR1001MG,USR1002,awareness,1/5/2022,successful,post_demo_followup

In [32]:
df3.isnull().sum()

jnr_sm_id         0
lead_id           0
lead_stage        0
call_done_date    0
call_status       0
call_reason       0
dtype: int64

In [34]:
df3.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2187    False
2188    False
2189    False
2190    False
2191    False
Length: 2192, dtype: bool

In [36]:
df3.shape

(2192, 6)

In [39]:
df3.columns

Index(['jnr_sm_id', 'lead_id', 'lead_stage', 'call_done_date', 'call_status',
       'call_reason'],
      dtype='object')

In [40]:
traduzido3 = {
'jnr_sm_id': 'id_gerente_junior',
'lead_id': 'id_lead',
'lead_stage': 'estagio_lead',
'call_done_date': 'data_da_ligacao',
'call_status': 'status_da_ligacao',
'call_reason': 'motivo_da_ligacao'
}
df3 = df3.rename(columns=traduzido3)

In [41]:
df3.head()

,id_gerente_junior,id_lead,estagio_lead,data_da_ligacao,status_da_ligacao,motivo_da_ligacao
0,JNR1001MG,USR1001,lead,1/2/2022,successful,lead_introduction
1,JNR1001MG,USR1001,lead,1/2/2022,successful,demo_schedule
2,JNR1001MG,USR1002,lead,1/3/2022,successful,lead_introduction
3,JNR1001MG,USR1002,lead,1/4/2022,successful,demo_schedule
4,JNR1001MG,USR1002,awareness,1/5/2022,successful,post_demo_followup

In [42]:
df4.head()

,id_lead,motivo_nao_demo,motivo_nao_consideracao,motivo_nao_conversao
0,USR1001,No time for student,NaN,NaN
1,USR1003,NaN,No time for student,NaN
2,USR1004,NaN,Wants offline classes,NaN
3,USR1005,NaN,Can't afford,NaN
4,USR1006,NaN,Student not interested in domain,NaN

In [46]:
df1.head()

,id_lead,idade,genero,cidade_atual,escolaridade_atual,ocupacao_pais,origem_lead
0,USR1001,16,FEMALE,Hyderabad,Intermediate,Private Employee,social_media
1,USR1002,20,MALE,Bengaluru,B.Tech,Business,user_referrals
2,USR1003,20,FEMALE,Visakhapatnam,B.Tech,Lawyer,user_referrals
3,USR1004,16,MALE,Mumbai,Intermediate,IT Employee,user_referrals
4,USR1005,16,MALE,Chennai,Intermediate,Government Employee,user_referrals

In [51]:
df4.head()

,id_lead,motivo_nao_demo,motivo_nao_consideracao,motivo_nao_conversao
0,USR1001,No time for student,NaN,NaN
1,USR1003,NaN,No time for student,NaN
2,USR1004,NaN,Wants offline classes,NaN
3,USR1005,NaN,Can't afford,NaN
4,USR1006,NaN,Student not interested in domain,NaN

In [57]:
df4 = df4.fillna('sem_info')

In [58]:
df4.head()

,id_lead,motivo_nao_demo,motivo_nao_consideracao,motivo_nao_conversao
0,USR1001,No time for student,sem_info,sem_info
1,USR1003,sem_info,No time for student,sem_info
2,USR1004,sem_info,Wants offline classes,sem_info
3,USR1005,sem_info,Can't afford,sem_info
4,USR1006,sem_info,Student not interested in domain,sem_info

In [63]:
df1.to_csv('leads_basic_details.csv')

In [64]:
df2.to_csv('leads_demo_watched_details.csv')
df3.to_csv('leads_interaction_details.csv')
df4.to_csv('leads_reasons_for_no_interest.csv')

In [65]:
df5.head()

  snr_sm_id  jnr_sm_id assigned_date  cycle  lead_id
0  SNR501MG  JNR1001MG      1/1/2022      1  USR1001
1  SNR501MG  JNR1001MG      1/1/2022      1  USR1002
2  SNR501MG  JNR1001MG      1/1/2022      1  USR1003
3  SNR501MG  JNR1001MG      1/1/2022      1  USR1004
4  SNR501MG  JNR1001MG      1/1/2022      1  USR1005

In [66]:
df5.isnull().sum()

snr_sm_id        0
jnr_sm_id        0
assigned_date    0
cycle            0
lead_id          0
dtype: int64

In [67]:
df5.duplicated().sum()

0

In [68]:
df5.columns

Index(['snr_sm_id', 'jnr_sm_id', 'assigned_date', 'cycle', 'lead_id'], dtype='object')

In [69]:
traduzido5 = {
    'snr_sm_id': 'id_gestor_vendas_senior',
    'jnr_sm_id': 'id_gestor_vendas_junior',
    'assigned_date': 'data_atribuicao',
    'cycle': 'ciclo',
    'lead_id': 'id_lead'
}

df5 = df5.rename(columns=traduzido5)

In [70]:
df5.head()

,id_gestor_vendas_senior,id_gestor_vendas_junior,data_atribuicao,ciclo,id_lead
0,SNR501MG,JNR1001MG,1/1/2022,1,USR1001
1,SNR501MG,JNR1001MG,1/1/2022,1,USR1002
2,SNR501MG,JNR1001MG,1/1/2022,1,USR1003
3,SNR501MG,JNR1001MG,1/1/2022,1,USR1004
4,SNR501MG,JNR1001MG,1/1/2022,1,USR1005

In [72]:
df5.to_csv('sales_managers_assigned_leads_details.csv')